# coding: utf-8
lib = File.expand_path("../lib", __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require "delfos/neo4j_analysis/version"

Gem::Specification.new do |spec|
  spec.name          = "delfos-neo4j_analysis"
  spec.version       = Delfos::Neo4jAnalysis::VERSION
  spec.authors       = ["Mark Burns"]
  spec.email         = ["markthedeveloper@gmail.com"]

  spec.summary       = %q{Tooling for analysing neo4j data generated by Delfos}
  spec.description   = %q{Command line tools for Delfos results}
  spec.homepage      = "https://github.com/ruby-analysis/delfos-neo4j_analysis"

  # Prevent pushing this gem to RubyGems.org. To allow pushes either set the 'allowed_push_host'
  # to allow pushing to a single host or delete this section to allow pushing to any host.
  if spec.respond_to?(:metadata)
    spec.metadata["allowed_push_host"] = "TODO: Set to 'http://mygemserver.com'"
  else
    raise "RubyGems 2.0 or newer is required to protect against " \
      "public gem pushes."
  end

  spec.files         = `git ls-files -z`.split("\x0").reject do |f|
    f.match(%r{^(test|spec|features)/})
  end
  spec.bindir        = "exe"
  spec.executables   = spec.files.grep(%r{^exe/}) { |f| File.basename(f) }
  spec.require_paths = ["lib"]

  spec.add_dependency "delfos"
  spec.add_dependency "values"
  spec.add_development_dependency "byebug"
  spec.add_development_dependency "bundler", "~> 1.15"
  spec.add_development_dependency "rspec", "~> 3.6"
  spec.add_development_dependency "rake", "~> 10.0"
end
