#!/usr/bin/env ruby
require "byebug"

$:.unshift File.expand_path("../../lib", __FILE__)
require "delfos/neo4j_analysis/cli"

path_prefix = ARGV[0] || ""
port = ENV["NEO4J_PORT"] || "8001"

Delfos::Neo4jAnalysis::Cli.start(port, path_prefix)
